let users = [
  {
    id: "user1",
    name: "Robert",
    lastName: "Mayer",
    age: 40,
    email: "rob_40@yahoo.edu",
    pasword: "may40",
    code: "andin.polo",
    verified: true,
    logged: true,
  },
  {
    id: "user2",
    name: "Micaela",
    lastName: "Allende",
    age: 30,
    email: "mic_all@icloud.net",
    pasword: "mic30",
    code: "mama.lila",
    verified: true,
    logged: true,
  },
  {
    id: "user3",
    name: "Bradley",
    lastName: "Henderson",
    age: 25,
    email: "brad_hend@aol.edu",
    pasword: "brad25",
    code: "vestibulum.brad",
    verified: true,
    logged: true,
  },
  {
    id: "user4",
    name: "Mary",
    lastName: "Cooper",
    age: 29,
    email: "mary_coop@hotmail.edu",
    pasword: "mary29",
    code: "awita.deuwu",
    verified: true,
    logged: true,
  },
];

export default users